name: Build test

on:
  workflow_dispatch:
  pull_request:  
  push:
    branches:
      - main
      - develop
      - feature-*
      - release-v*
      - hotfix-*
      - bugfix-m-*
      - bugfix-*
      - feature/**
      - release/v**
      - hotfix/**
      - bugfix-m/**
      - bugfix/**
    paths-ignore:
      - '.gitignore'
      #- 'README.md'
      #- '.github'    

jobs:
  prepare:
    name: Generate Artifact Name    
    uses: ./.github/workflows/artifacts.yml    

  build:
    needs: [prepare]   
    uses: ./.github/workflows/artifacts.yml
    with:
      product: 'test'
    secrets: inherit
    